/** S&P 500 대형주 중심 투자 유니버스 (동일 기준 적용) */
export const QUANT_UNIVERSE: { ticker: string; name: string }[] = [
  { ticker: "AAPL", name: "Apple" },
  { ticker: "MSFT", name: "Microsoft" },
  { ticker: "GOOGL", name: "Alphabet" },
  { ticker: "AMZN", name: "Amazon" },
  { ticker: "NVDA", name: "NVIDIA" },
  { ticker: "META", name: "Meta Platforms" },
  { ticker: "TSLA", name: "Tesla" },
  { ticker: "BRK-B", name: "Berkshire Hathaway" },
  { ticker: "JPM", name: "JPMorgan Chase" },
  { ticker: "V", name: "Visa" },
  { ticker: "UNH", name: "UnitedHealth" },
  { ticker: "MA", name: "Mastercard" },
  { ticker: "HD", name: "Home Depot" },
  { ticker: "PG", name: "Procter & Gamble" },
  { ticker: "JNJ", name: "Johnson & Johnson" },
  { ticker: "XOM", name: "Exxon Mobil" },
  { ticker: "AVGO", name: "Broadcom" },
  { ticker: "LLY", name: "Eli Lilly" },
  { ticker: "COST", name: "Costco" },
  { ticker: "MRK", name: "Merck" },
  { ticker: "ABBV", name: "AbbVie" },
  { ticker: "PEP", name: "PepsiCo" },
  { ticker: "KO", name: "Coca-Cola" },
  { ticker: "WMT", name: "Walmart" },
  { ticker: "BAC", name: "Bank of America" },
  { ticker: "CRM", name: "Salesforce" },
  { ticker: "AMD", name: "Advanced Micro Devices" },
  { ticker: "ORCL", name: "Oracle" },
  { ticker: "NFLX", name: "Netflix" },
  { ticker: "ADBE", name: "Adobe" },
  { ticker: "DIS", name: "Walt Disney" },
  { ticker: "INTC", name: "Intel" },
  { ticker: "CSCO", name: "Cisco" },
  { ticker: "TMO", name: "Thermo Fisher" },
  { ticker: "ACN", name: "Accenture" },
  { ticker: "MCD", name: "McDonald's" },
  { ticker: "ABT", name: "Abbott" },
  { ticker: "DHR", name: "Danaher" },
  { ticker: "TXN", name: "Texas Instruments" },
  { ticker: "PM", name: "Philip Morris" },
  { ticker: "NEE", name: "NextEra Energy" },
  { ticker: "LIN", name: "Linde" },
  { ticker: "RTX", name: "RTX" },
  { ticker: "HON", name: "Honeywell" },
  { ticker: "QCOM", name: "Qualcomm" },
  { ticker: "IBM", name: "IBM" },
  { ticker: "AMGN", name: "Amgen" },
  { ticker: "LOW", name: "Lowe's" },
  { ticker: "CAT", name: "Caterpillar" },
  { ticker: "GE", name: "GE Aerospace" },
  { ticker: "SPGI", name: "S&P Global" },
  { ticker: "BLK", name: "BlackRock" },
  { ticker: "GS", name: "Goldman Sachs" },
  { ticker: "MS", name: "Morgan Stanley" },
  { ticker: "AXP", name: "American Express" },
  { ticker: "SYK", name: "Stryker" },
  { ticker: "DE", name: "Deere" },
  { ticker: "MDT", name: "Medtronic" },
  { ticker: "GILD", name: "Gilead Sciences" },
  { ticker: "CVX", name: "Chevron" },
  { ticker: "PFE", name: "Pfizer" },
  { ticker: "T", name: "AT&T" },
  { ticker: "VZ", name: "Verizon" },
  { ticker: "CMCSA", name: "Comcast" },
  { ticker: "SBUX", name: "Starbucks" },
  { ticker: "BKNG", name: "Booking Holdings" },
  { ticker: "ISRG", name: "Intuitive Surgical" },
  { ticker: "NOW", name: "ServiceNow" },
  { ticker: "PANW", name: "Palo Alto Networks" },
  { ticker: "MU", name: "Micron Technology" },
  { ticker: "LRCX", name: "Lam Research" },
  { ticker: "KLAC", name: "KLA" },
  { ticker: "SNPS", name: "Synopsys" },
  { ticker: "CDNS", name: "Cadence Design" },
  { ticker: "ADI", name: "Analog Devices" },
  { ticker: "REGN", name: "Regeneron" },
  { ticker: "VRTX", name: "Vertex Pharma" },
  { ticker: "BMY", name: "Bristol-Myers Squibb" },
  { ticker: "CI", name: "Cigna" },
  { ticker: "SO", name: "Southern Company" },
  { ticker: "DUK", name: "Duke Energy" },
  { ticker: "CL", name: "Colgate-Palmolive" },
  { ticker: "MO", name: "Altria" },
];

export const BENCHMARK_TICKER = "SPY";

export const UNIVERSE_TICKERS = QUANT_UNIVERSE.map((s) => s.ticker);

export const UNIVERSE_NAMES = Object.fromEntries(
  QUANT_UNIVERSE.map((s) => [s.ticker, s.name])
);
